SBMS/Controllers/ReportingController.cs
using SBMS.BLL.BLL;
using SBMS.Models;
using SBMS.Models.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;

namespace SBMS.Controllers
{
    public class ReportingController : Controller
    {
        ProductManager _productManager = new ProductManager();
        ReportingManager _reportingManager = new ReportingManager();
        PurchaseManager _purchseManager = new PurchaseManager();
        SalesManager _salesManager = new SalesManager();
        private Product _product = new Product();

        // GET: Reporting
        [HttpGet]
        public ActionResult PeriodictIncomeReport()
        {

            return View();

        }

        [HttpPost]
        public ActionResult PeriodictIncomeReport(ProductViewModel productViewModel)
        {
            List<ProductViewModel> productViewModels = new List<ProductViewModel>();
            List<ProductViewModel> productsPreviousRecord = new List<ProductViewModel>();

            var products = _productManager.GetAll();
            foreach (var product in products)
            {
                var aProduct = _purchseManager.GetByPrevious(product);
                productsPreviousRecord.Add(aProduct);
            }
            var sale = Mapper.Map<ProductVM>(productViewModel);
            var salesProducts = _reportingManager.PeriodictIncomeReport(sale);
            foreach (var saleProduct in salesProducts)
            {
                ProductViewModel model = new ProductViewModel();

                var product = productsPreviousRecord.Where(c => c.ProductId == saleProduct.ProductId).FirstOrDefault();
                _product.Id = product.ProductId;
                var aProduct = _productManager.GetByID(_product);
                model.Code = aProduct.Code;
                model.Name = aProduct.Name;
                model.CategoryName = aProduct.Category.Name;
                model.TotalCostPrice = product.PreviousCostPrice * saleProduct.Quantity;
                model.SalesPrice = product.PreviousMRP * saleProduct.Quantity;
                model.Profit = model.SalesPrice - model.TotalCostPrice;
                productViewModels.Add(model);
            }
            foreach (var model in productViewModels)
            {
                ProductViewModel aModel = new ProductViewModel();

                if (productViewModel.ProductsView != null && productViewModel.ProductsView.Count > 0)
                {
                    int count = 0;
                    int countValue = productViewModel.ProductsView.Count;
                    foreach (var p in productViewModel.ProductsView)
                    {
                        count++;
                        if (p.Name == model.Name)
                        {
                            p.TotalCostPrice += model.TotalCostPrice;
                            p.SalesPrice += model.SalesPrice;
                            p.Profit += model.Profit;
                            break;
                        }
                        else
                        {
                            if (count == countValue)
                            {
                                aModel.Code = model.Code;
                                aModel.Name = model.Name;
                                aModel.CategoryName = model.CategoryName;
                                aModel.TotalCostPrice = model.TotalCostPrice;
                                aModel.SalesPrice = model.SalesPrice;
                                aModel.Profit = model.Profit;
                                productViewModel.ProductsView.Add(aModel);
                                break;
                            }
                        }
                    }
                }
                else
                {
                    aModel.Code = model.Code;
                    aModel.Name = model.Name;
                    aModel.CategoryName = model.CategoryName;
                    aModel.TotalCostPrice = model.TotalCostPrice;
                    aModel.SalesPrice = model.SalesPrice;
                    aModel.Profit = model.Profit;
                    productViewModel.ProductsView.Add(aModel);
                }

            }
            return View(productViewModel);
        }

        [HttpGet]
        public ActionResult PeriodicIncomeExpenseOnPurchase()
        {

            return View();

        }

        [HttpPost]
        public ActionResult PeriodicIncomeExpenseOnPurchase(ProductViewModel productViewModel)
        {
            List<ProductViewModel> productViewModels = new List<ProductViewModel>();
            List<ProductViewModel> productsPreviousRecord = new List<ProductViewModel>();

            var products = _productManager.GetAll();
            foreach (var product in products)
            {
                var aProduct = _purchseManager.GetByPrevious(product);
                productsPreviousRecord.Add(aProduct);
            }
            var x = Mapper.Map<ProductVM>(productViewModel);
            var purchaseProducts = _reportingManager.PeriodictIncomeReportOnPurchase(x);
            foreach (var purchaseProduct in purchaseProducts)
            {
                ProductViewModel model = new ProductViewModel();

                var product = productsPreviousRecord.Where(c => c.ProductId == purchaseProduct.ProductId).FirstOrDefault();
                _product.Id = product.ProductId;
                int availableQuantity = _salesManager.GetBySalesQuantity(_product);
                var aProduct = _productManager.GetByID(_product);
                model.Code = aProduct.Code;
                model.Name = aProduct.Name;
                model.CategoryName = aProduct.Category.Name;
                model.TotalCostPrice = product.PreviousCostPrice * availableQuantity;
                model.SalesPrice = product.PreviousMRP * availableQuantity;
                model.Profit = model.SalesPrice - model.TotalCostPrice;
                productViewModels.Add(model);
            }
            foreach (var model in productViewModels)
            {
                ProductViewModel aModel = new ProductViewModel();

                if (productViewModel.ProductsView != null && productViewModel.ProductsView.Count > 0)
                {
                    int count = 0;
                    int countValue = productViewModel.ProductsView.Count;
                    foreach (var p in productViewModel.ProductsView)
                    {
                        count++;
                        if (p.Name == model.Name)
                        {
                            p.TotalCostPrice += model.TotalCostPrice;
                            p.SalesPrice += model.SalesPrice;
                            p.Profit += model.Profit;
                            break;
                        }
                        else
                        {
                            if (count == countValue)
                            {
                                aModel.Code = model.Code;
                                aModel.Name = model.Name;
                                aModel.CategoryName = model.CategoryName;
                                aModel.TotalCostPrice = model.TotalCostPrice;
                                aModel.SalesPrice = model.SalesPrice;
                                aModel.Profit = model.Profit;
                                productViewModel.ProductsView.Add(aModel);
                                break;
                            }
                        }
                    }
                }
                else
                {
                    aModel.Code = model.Code;
                    aModel.Name = model.Name;
                    aModel.CategoryName = model.CategoryName;
                    aModel.TotalCostPrice = model.TotalCostPrice;
                    aModel.SalesPrice = model.SalesPrice;
                    aModel.Profit = model.Profit;
                    productViewModel.ProductsView.Add(aModel);
                }

            }
            return View(productViewModel);
        }
    }
}

SBMS/Views/Reporting/PeriodicIncomeExpenseOnPurchase.cshtml
@model SBMS.Models.ProductViewModel
@{
    ViewBag.Title = "PeriodicIncomeExpenseOnPurchase";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div id="periodicIncomeExpenseOnPurchase" class="container text-center">
    <h3>Periodic Income Expense On Purchase</h3>


    @using (Html.BeginForm("PeriodicIncomeExpenseOnPurchase", "Reporting"))
    {

        <div class="row">
            <br />
            <div class="col-md-12" style="background: black"></div>
            <div class="col-md-12" style="background: aquamarine"></div>
            <div class="form-horizontal">
                <h4 class="h-position">Expense Report On Purchase </h4>
                <hr class="hr-design">

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div>
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.StartDate, new { @class = "control-label col-md-3" })
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" }, @value = DateTime.Now })
                                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.EndDate, new { @class = "control-label col-md-3" })
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" }, @value = DateTime.Now })
                                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-8 col-md-4">
                                <input type="submit" value="Search" class="btn btn-info" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-12" style="background: black"></div>
            <div class="col-md-12" style="background: aquamarine"></div>
        </div>

    }
    <div class="row">
        <br />
        <div class="col-md-12" style="background: black"></div>
        <div class="col-md-12" style="background: aquamarine"></div>

        <table class="table table-bordered table-striped table-hover table-responsive">
            <thead>
                <tr>
                    <th>SL</th>
                    <th>
                        @Html.DisplayNameFor(model => model.Code)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.CategoryId)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.TotalCostPrice)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.SalesPrice)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Profit)
                    </th>
                </tr>

            </thead>
            @if (Model != null)
            {
                <tbody>
                    @{ int sl = 1;}
                    @foreach (var item in Model.ProductsView)
                    {
                        <tr>
                            <td>
                                @(sl++)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Code)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.CategoryName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.TotalCostPrice)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.SalesPrice)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Profit)
                            </td>
                        </tr>
                    }
                </tbody>
            }
        </table>

        <div class="col-md-12" style="background: black"></div>
        <div class="col-md-12" style="background: aquamarine"></div>
    </div>



</div>

SBMS/Views/Reporting/PeriodictIncomeReport.cshtml
@model SBMS.Models.ProductViewModel
@{
    ViewBag.Title = "PeriodictIncomeReport";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div id="periodicIncomeExpenseOnPurchase" class="container text-center">
    <h3>Periodic Income Expense Report on Sales</h3>

    @using (Html.BeginForm("PeriodictIncomeReport", "Reporting"))
    {

        <div class="row">
            <br />
            <div class="col-md-12" style="background: black"></div>
            <div class="col-md-12" style="background: aquamarine"></div>

            <div class="form-horizontal">
                <h4 class="h-position">Expense Report on Sales</h4>
                <hr class="hr-design">

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div>
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.StartDate, new { @class = "control-label col-md-3" })
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" }, @value = DateTime.Now })
                                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.EndDate, new { @class = "control-label col-md-3" })
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" }, @value = DateTime.Now })
                                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-8 col-md-4">
                                <input type="submit" value="Search" class="btn btn-info" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-12" style="background: black"></div>
            <div class="col-md-12" style="background: aquamarine"></div>
        </div>


    }

    <div class="row">
        <br />
        <div class="col-md-12" style="background: black"></div>
        <div class="col-md-12" style="background: aquamarine"></div>

        <table class="table table-bordered table-striped table-hover table-responsive">
            <thead>
                <tr>
                    <th>SL</th>
                    <th>
                        @Html.DisplayNameFor(model => model.Code)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.CategoryId)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.TotalCostPrice)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.SalesPrice)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Profit)
                    </th>
                </tr>

            </thead>
            @if (Model != null)
            {
                <tbody>
                    @{ int sl = 1;}
                    @foreach (var item in Model.ProductsView)
                    {
                        <tr>
                            <td>
                                @(sl++)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Code)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.CategoryName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.TotalCostPrice)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.SalesPrice)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Profit)
                            </td>
                        </tr>
                    }
                </tbody>
            }
        </table>

        <div class="col-md-12" style="background: black"></div>
        <div class="col-md-12" style="background: aquamarine"></div>
    </div>


</div>